### ISSUE TITLE
is it supporting cdn?

### ISSUE THREAD

**Issue by ericxin1982** [prettyblueberry/mui-datagrid-full-edit#5]
Hi,

It is supporting cdn way, like add it through script src globally?

Thanks
Eric Xin

**Comment by prettyblueberry** [comment]
Hi Eric,

Thank you for your issue and sorry for my late response.
For right now, it is not supporting CDN way.

But I will provide it soon considering your opinion.

Thank you again.

**Comment by ericxin1982** [comment]
Thanks for reply.

**Comment by prettyblueberry** [comment]
Hi Eric,

Could you provide a guide?
Sorry, I don't know how to publish reusable react component via CDN.

Thank you very much in advance.

**Comment by ericxin1982** [comment]
Hi @prettyblueberry 

I am user, I have no idea also. Sorry.

Thanks
Eric Xin
